### ISSUE TITLE
UserManagement showing "externalError":"no such command: 'lsid'"

### ISSUE THREAD

**Issue by mr-devop** [nosqlclient/nosqlclient#502]
When I click on UserManagement or click refresh on the usermanagement page. I am getting the error on the UI:
```
[1009] no such command: 'lsid'
```

And this error in the backend:
```
nosqlclient      | {"methodArray":[{"command":["",{}]}],"runOnAdminDB":false,"sessionId":"QcZncST6teHqMFXnK","level":"info","message":"[admin-query-execution]"}
nosqlclient      | {"externalError":"no such command: 'lsid'","methodArray":[{"command":["",{},null]}],"runOnAdminDB":false,"sessionId":"QcZncST6teHqMFXnK","level":"error","message":"[query-error]"}
```

I am connecting as the Admin user to MongoDB 4.1 (container `mongo:4.1`) I am using the latest nosqlclient container `mongoclient/mongoclient`
## Expected Behavior
The ability to manage users etc.

## Current Behavior
Cant do anything to manage users. Only recieve that error.

## Steps to Reproduce (for bugs)
This is my docker-compose.yml file:
```
version: '3.1'

services:

  mongo:
    image: mongo:4.1
    hostname: mongodb
    container_name: mongodb
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: example
    ports:
      - 27017:27017
    volumes:
      - ./mongod.conf:/etc/mongo/mongod.conf
      - ./dbdata:/data/db
    command:
      - --config
      - /etc/mongo/mongod.conf

  nosqlclient:
    image: mongoclient/mongoclient
    container_name: nosqlclient
    hostname: nosqlclient
    ports:
      - 3000:3000
    volumes:
      - ./nosqlclientData:/data/db
```

Connect to `mongodb://root:example@mongo:27017`  go to `UserManagement`

## Context
Was just testing the product. Wanted to see if I could admin users easily via the UI

## Your Environment

* Nosqlclient version used: latest container `mongoclient/mongoclient`
* Environment name: docker 
* Operating System and version (e.g. windows 10, ubuntu 16, osx 10.12): running on docker-compose on a macbook pro

**Comment by rsercano** [comment]
Thank you for details, checking it right away.

**Comment by mr-devop** [comment]
@rsercano I forgot to add. This is the `mongod.conf` file that I mount into the `mongo` container:
```
# mongod.conf

# network interfaces
net:
  port: 27017
  bindIp: 0.0.0.0
```
