### ISSUE TITLE
Docker nginx reverse proxy, images not found

### ISSUE THREAD

**Issue by firecow** [nosqlclient/nosqlclient#507]
I have a docker setup with a running Mongo DB, need to reverse proxy to NoSQLClient docker container, because of ldap auth service.
But images not being found as shown in the screenshot.

vhost.conf
```
location /tools/nosqlclient/ {
    auth_basic "LDAP";
    auth_basic_user_file /etc/nginx/.htpasswd;

    set $nosqlclient_upstream http://nosqlclient:3000;
    #rewrite /tools/nosqlclient/(.*) /$1  break;
    proxy_pass $nosqlclient_upstream;
    proxy_http_version 1.1;
    proxy_set_header Upgrade $http_upgrade;
    proxy_set_header Connection 'upgrade';
    proxy_set_header Host $host;
    proxy_cache_bypass $http_upgrade;
}
```

docker-compose.yml
```
nosqlclient:
    image: mongoclient/mongoclient:2.2.0
    environment:
      - MONGO_URL=mongodb://mongo
      - ROOT_URL=http://localhost/tools/nosqlclient
      - INSTALL_MONGO=false
```
Can you guys spot any obvious errors in this setup ?

![nosqlclient](https://user-images.githubusercontent.com/973602/58863345-f7ba6780-86b2-11e9-952b-36161404f846.png)
