### ISSUE TITLE
[Kube] EISDIR: illegal operation on a directory

### ISSUE THREAD

**Issue by ChapChap** [nosqlclient/nosqlclient#539]
[Kube] EISDIR: illegal operation on a directory

## Expected Behavior
```console
NAME                                           READY     STATUS    RESTARTS   AGE
nosqlclient-ocjz-deployment-56b94b8dbd-spkvb   1/1       Running   0          19s
AME                          READY     UP-TO-DATE   AVAILABLE   AGE
nosqlclient-ocjz-deployment   1/1       1            1           69s
```

## Current Behavior

```console
NAME                          READY     UP-TO-DATE   AVAILABLE   AGE
nosqlclient-ocjz-deployment   0/1       1            0           3m26s
NAME                                           READY     STATUS    RESTARTS   AGE
nosqlclient-ocjz-deployment-56b94b8dbd-spkvb   1/1       Running   1          27s
```

```console
    State:          Waiting
      Reason:       CrashLoopBackOff
    Last State:     Terminated
      Reason:       StartError
      Message:      failed to create containerd task: OCI runtime create failed: container_linux.go:349: starting container process caused "exec: \"./entrypoint.sh\": stat ./entrypoint.sh: no such file or directory": unknown
      Exit Code:    128
      Started:      Thu, 01 Jan 1970 01:00:00 +0100
      Finished:     Tue, 21 Apr 2020 17:31:01 +0200
    Ready:          False
    Restart Count:  2
```

```json
{
	"error": {
		"errno": -21,
		"code": "EISDIR",
		"syscall": "read"
	},
	"level": "error",
	"message": "uncaughtException: EISDIR: illegal operation on a directory, read\nError: EISDIR: illegal operation on a directory, read\n    at Object.fs.readSync (fs.js:681:18)\n    at tryReadSync (fs.js:542:20)\n    at Object.fs.readFileSync (fs.js:585:19)\n    at Connection.savePredefinedConnections (server/imports/core/connection/index.js:269:28)\n    at Meteor.startup (server/imports/core/startup/startup.js:33:14)\n    at Function.time (/opt/meteor/dist/bundle/programs/server/profile.js:309:28)\n    at /opt/meteor/dist/bundle/programs/server/boot.js:435:13\n    at /opt/meteor/dist/bundle/programs/server/boot.js:480:5\n    at Function.run (/opt/meteor/dist/bundle/programs/server/profile.js:510:12)\n    at /opt/meteor/dist/bundle/programs/server/boot.js:478:11",
	"stack": "Error: EISDIR: illegal operation on a directory, read\n    at Object.fs.readSync (fs.js:681:18)\n    at tryReadSync (fs.js:542:20)\n    at Object.fs.readFileSync (fs.js:585:19)\n    at Connection.savePredefinedConnections (server/imports/core/connection/index.js:269:28)\n    at Meteor.startup (server/imports/core/startup/startup.js:33:14)\n    at Function.time (/opt/meteor/dist/bundle/programs/server/profile.js:309:28)\n    at /opt/meteor/dist/bundle/programs/server/boot.js:435:13\n    at /opt/meteor/dist/bundle/programs/server/boot.js:480:5\n    at Function.run (/opt/meteor/dist/bundle/programs/server/profile.js:510:12)\n    at /opt/meteor/dist/bundle/programs/server/boot.js:478:11",
	"exception": true,
	"date": "Tue Apr 21 2020 16:11:23 GMT+0000 (UTC)",
	"process": {
		"pid": 1,
		"uid": 1000,
		"gid": 1000,
		"cwd": "/opt/meteor/dist/bundle/programs/server",
		"execPath": "/opt/nodejs/bin/node",
		"version": "v8.4.0",
		"argv": ["/opt/nodejs/bin/node", "/opt/meteor/dist/bundle/main.js", "program.json"],
		"memoryUsage": {
			"rss": 116068352,
			"heapTotal": 85377024,
			"heapUsed": 56072344,
			"external": 58444186
		}
	},
	"os": {
		"loadavg": [1.12353515625, 0.4951171875, 0.34375],
		"uptime": 3719724
	},
	"trace": [{
		"column": 18,
		"file": "fs.js",
		"function": "Object.fs.readSync",
		"line": 681,
		"method": "readSync",
		"native": false
	}, {
		"column": 20,
		"file": "fs.js",
		"function": "tryReadSync",
		"line": 542,
		"method": null,
		"native": false
	}, {
		"column": 19,
		"file": "fs.js",
		"function": "Object.fs.readFileSync",
		"line": 585,
		"method": "readFileSync",
		"native": false
	}, {
		"column": 28,
		"file": "server/imports/core/connection/index.js",
		"function": "Connection.savePredefinedConnections",
		"line": 269,
		"method": "savePredefinedConnections",
		"native": false
	}, {
		"column": 14,
		"file": "server/imports/core/startup/startup.js",
		"function": "Meteor.startup",
		"line": 33,
		"method": "startup",
		"native": false
	}, {
		"column": 28,
		"file": "/opt/meteor/dist/bundle/programs/server/profile.js",
		"function": "Function.time",
		"line": 309,
		"method": "time",
		"native": false
	}, {
		"column": 13,
		"file": "/opt/meteor/dist/bundle/programs/server/boot.js",
		"function": null,
		"line": 435,
		"method": null,
		"native": false
	}, {
		"column": 5,
		"file": "/opt/meteor/dist/bundle/programs/server/boot.js",
		"function": null,
		"line": 480,
		"method": null,
		"native": false
	}, {
		"column": 12,
		"file": "/opt/meteor/dist/bundle/programs/server/profile.js",
		"function": "Function.run",
		"line": 510,
		"method": "run",
		"native": false
	}, {
		"column": 11,
		"file": "/opt/meteor/dist/bundle/programs/server/boot.js",
		"function": null,
		"line": 478,
		"method": null,
		"native": false
	}]
}
```
## Steps to Reproduce (for bugs)
Here is my deployment :
```yaml
---
apiVersion: v1
data:
  nosqlclient-ocjz-servers: |
    [
      {
        "name": "test",
        "url": "mongodb://mongodb0.prod.com:27017/admin"
      },
      {
        "name": "test2",
        "url": "mongodb://mongodb0.test.com:27017/admin"
      }
    ]
kind: ConfigMap
metadata:
  name: nosqlclient-ocjz-cm
---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: nosqlclient-ocjz
    appcode: <value>
    opscontact: <value>
    tier: <value>
  name: nosqlclient-ocjz-deployment
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: nosqlclient-ocjz
        appcode: <value>
        opscontact: <value>
        tier: <value>
    spec:
      securityContext:
          runAsUser: 1000
          runAsGroup: 1000
          fsGroup: 1000
      containers:
      - image: <value>/mongoclient:latest
#        env:
#          - name: MONGOCLIENT_CONNECTIONS_FILE_PATH
#            value: /opt/meteor/dist/predefined_connections.json
        imagePullPolicy: Always
        name: nosqlclient-ocjz-container
        ports:
        - containerPort: 3000
          protocol: TCP
        resources:
          limits:
            cpu: 200m
            memory: 400Mi
          requests:
            cpu: 100m
            memory: 256Mi
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
        volumeMounts:
        - mountPath: /var/log/
          name: nosqlclient-ocjz-logs
        - mountPath: /data/db/
          name: nosqlclient-ocjz-db
        - mountPath: /tmp
          name: nosqlclient-ocjz-tmp
        - mountPath: /opt/meteor/dist/predefined_connections.json
          name: nosqlclient-ocjz-servers
          subPath: predefined_connections.json
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      schedulerName: default-scheduler
      #securityContext: {}
      terminationGracePeriodSeconds: 30
      volumes:
      - emptyDir: {}
        name: nosqlclient-ocjz-tmp
      - emptyDir: {}
        name: nosqlclient-ocjz-db
      - emptyDir: {}
        name: nosqlclient-ocjz-logs
      - name: nosqlclient-ocjz-servers
        configMap:
          name: nosqlclient-ocjz-cm
          items:
          - key: nosqlclient-ocjz-servers
            path: servers.json
  selector:
    matchLabels:
      app: nosqlclient-ocjz
      appcode: <value>
      opscontact: <value>
      tier: <value>

---

apiVersion: v1
kind: Service
metadata:
  name: nosqlclient-ocjz-service

spec:
  ports:
  - port: 80
    protocol: TCP
    targetPort: 3000
  selector:
    app: nosqlclient-ocjz
    appcode: <value>
    opscontact: <value>
    tier: <value>

  type: ClusterIP

---
apiVersion: extensions/v1beta1
kind: Ingress
[...]
---
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
[...]
```

## Context
I am trying to run the image in a Public Cloud Kube cluster
Due to RO restriction, I think the execution within /opt is blocked.
Is there a way to make it work? writing to an emptydir in kube ?

## Your Environment
```console
root@s00vl9996922:icp# kubectl version
Client Version: version.Info{Major:"1", Minor:"11", GitVersion:"v1.11.1", GitCommit:"b1b29978270dc22fecc592ac55d903350454310a", GitTreeState:"clean", BuildDate:"2018-07-17T18:53:20Z", GoVersion:"go1.10.3", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"15", GitVersion:"v1.15.11+IKS", GitCommit:"0562ba8a2dfdd05f7f8721ab4952c02fe1605860", GitTreeState:"clean", BuildDate:"2020-03-13T14:45:42Z", GoVersion:"go1.12.17", Compiler:"gc", Platform:"linux/amd64"}
```
