### ISSUE TITLE
Connect to localhost of Docker host

### ISSUE THREAD

**Issue by Ekliptor** [nosqlclient/nosqlclient#542]
How can I connect to MongoDB running on `localhost` of the Docker host?

I am running:
`docker run -d -p 3010:3000 --network host -v /Users/daniel/Library/mongoclient:/data/db --env-file=/Users/daniel/.mongo_env mongoclient/mongoclient`
Notice the `--network host`

with `.mongo_enf` file:
```
MONGO_URL=mongodb://User:password@localhost:27017/myDB
```

This file works when specifying a `MONGO_URL` of an external IP address.
With localhost the Docker container terminates immediately (no error message displayed). Any ideas?

**Comment by rsercano** [comment]
Hello @Ekliptor 

I believe docker is connecting to network after startup, but `MONGO_URL` is being used before startup for nosqlclient's internal storage, so you may use another docker container of mongodb for that part I suppose. 

Btw. you don't have to specify `MONGO_URL`, nosqlclient will start it's own and connect to it, you can just use the binded volume every time to keep your connections etc.

**Comment by Ekliptor** [comment]
Thx for the fast reply.

I want to use another Mongo DB database I have on my local machine. So the easiest solution would be to move that to a 2nd Docker container and use Docker compose.

Would be helpful if you provided some more example setup files.

**Comment by rsercano** [comment]
I personally not really good at docker clusters, just using nosqlclient without an orcehstration for myself, on the other hand I know a lot of people using nosqlclient with compose and kubernetes, the problem is I'm not really familiar with those, sorry

**Comment by Ekliptor** [comment]
Thx for your quick help.

I solved it by moving my existing mongodb data from the host machine to a 2nd Docker container as this:

docker-compose.yml
```
version: "3.3"

services:
  mongo:
    image: mongo:latest
    volumes:
      - db_data:/data/db
    ports:
      - "37017:27017"
    restart: always

  nosqlclient:
    depends_on:
      - mongo
    image: mongoclient/mongoclient:latest
    ports:
      - "3010:3000"
    restart: always
    environment:
      MONGO_URL: mongodb://mongo:27017/sd_index

volumes:
  db_data:
    external: false
```
