### ISSUE TITLE
MONGO_URL environment variable not creating connection

### ISSUE THREAD

**Issue by nemkin** [nosqlclient/nosqlclient#552]
Hi!

I'm trying to run a mongodb and a mongoclient together using docker-compose. I would like to use the MONGO_URL environment variable to connect the mongoclient to the mongodb instance on docker-compose up, however the connection is not created from the environment variable.

## Steps to Reproduce (for bugs)
Save this docker-compose.yaml, and run docker-compose up.
```
version: "2"
services:
  mongo:
    image: bitnami/mongodb
    ports:
      - "27017:27017"
    networks:
      - mongonet
    healthcheck:
        test: echo 'db.runCommand("ping").ok' | mongo mongo:27017/test --quiet
        interval: 10s
        timeout: 10s
        retries: 5
        start_period: 40s
  mongoclient:
    image: mongoclient/mongoclient
    ports:
      - "3000:3000"
    networks:
      - mongonet
    environment:
      - MONGO_URL="mongodb://mongo:27017"
    depends_on:
      mongo:
        condition: service_healthy
networks:
  mongonet:

```

## Expected Behavior
Mongoclient should create a connection from MONGO_URL.

## Current Behavior
No connection is created in mongoclient. If I manually add the connection like this, it connects successfully:
![image](https://user-images.githubusercontent.com/25765636/102233193-496ebf80-3ef0-11eb-9725-40d5428320c7.png)

## Context
Found a [similar issue](https://github.com/nosqlclient/nosqlclient/issues/524), however it's closed as done in 4.0.0 and I'm using 4.0.1 (latest).

## Your Environment
* Nosqlclient version used: docker image mongoclient/mongoclient:4.0.1 (currently latest)
* Environment name: docker
* Operating System and version: windows 10

Thank you!
